### ISSUE TITLE
Renaming classes in units

### ISSUE THREAD

**Issue by FinnStokes** [ILAFF/ILAFF#9]
I know Rob was uncomfortable with the current class names in the units module, and I ran into some awkwardness when writing the documentation. Here is my proposed alternative:

- `Quantity` is the main class (previously called `Value`). Each quantity has:
  - a value (which is a float, numpy array or similar),
  - a `Dimension`
  - a `Scale`
- `Dimension` simply tracks the mass dimension of the quantity as an integer, though it could be generalised to include fractional mass dimensions other dimensionalities for to allow e.g. SI units
- `Scale` indicates how the physical scale of the quantities is set, current options are:
  - `Physical` quantites are stored in terms of powers of GeV and are compatible with all other physical quantities (hence, all instances of `Physical` compare equal)
  - `Lattice` quantities are stored in terms of powers of the lattice spacing and are only compatible with qunatities defined on the same lattice (corresponding to an instance of the `Lattice` class, hence different instances of `Lattice` do not compare equal)
- units are simply specific quantities that correspond to some unit of measure. Currently we define
  - `fm`, `GeV`, `MeV` are constants corresponding to SI units with a `Physical` scale
  - `a` is a method that returns a unit corresponding to the lattice spacing in a given `Lattice` scale

What do people think about this convention? Does it resolve your issues Rob?

**Comment by robertjperry** [comment]
I think the change Value -> Quantity is a nice one. A Quantity having a value and associated units makes sense to me. I am in favour of this change.

**Comment by FinnStokes** [comment]
What do you think about the other change (`Unit` -> `Dimension`)? I think I prefer it because the unit is closer to a combination of dimension and scale, and it means we can refer to `fm`, `GeV`, etc as units without causing confusion.

**Comment by robertjperry** [comment]
It's a little hard to say for me without using the code, but it sounds on the face of it more intuitive. Is it possible to push a version to git with the changes so we can try it out?
